asdf-community/asdf-direnv

.github/workflows/workflow.yml, README.md, shims/direnv_use_asdf, test/test_helpers.bash, test/use_asdf.bats
In your `.envrc` file now you can do: `use asdf current`.
And it will load the same plugins and versions as listed by
the output of `asdf current`.
Notice that `use asdf current` is a bit slow since it will
try to determine the version for each installed plugin
(same thing that `asdf current` does). But, the upside is
that you will have not only local plugins active but also
those in global ~/.tool-versions file (as resolved by asdf).
This means `use asdf current` will also activate plugins
that use legacy files and thus are not present inside
`.tool-versions`. (this was a limitation of `use asdf local`)
The old behaviour is now named `use asdf local` and is
currently still the default if you give no args to `use asdf`.
This is because `use asdf current` is slower, and I'm not
sure all …
=> New feature `use asdf current` to activate current plugins.

README.md
The current instructions place `asdf` as last in PATH and requires one to run `asdf exec` for anything which is increasingly furstrating
=> Fixes search PATH to make more sense

README.md
asdf direnv triggers a dirname error
=> use `asdf exec direnv` in .bashrc

bin/direnv_use_asdf, test/use_asdf.bats
I'm not sure if this is intended or not, current implementation ignores multiple versions with same plugin. For example:
```
direnv 2.21.2
python 3.8.2
python 2.7.17 # ignored
/root/.asdf/plugins/direnv/shims
/root/.asdf/installs/direnv/2.21.2/bin
/root/.asdf/installs/python/3.8.2/bin
/root/.asdf/bin
```
```
direnv 2.21.2
python 3.8.2 2.7.17 # both versions are ignored
/root/.asdf/plugins/direnv/shims
/root/.asdf/installs/direnv/2.21.2/bin
/root/.asdf/installs/python/3.8.2
/root/.asdf/installs/direnv/2.21.2/env/2.7.17/bin
/root/.asdf/bin
```
I think changing `_load_plugin_version_and_file` to ensure multiple versions for same plugin can fixes #44 🙂
=> Ensure multiple versions when loading plugin

bin/direnv_use_asdf
asdf renamed bash scripts to .bash, causing an error with `use asdf`
=> Update asdf script extension .sh -> .bash

shims/direnv_use_asdf
The `direnv_use_asdf` shim currently tries to source the result of `direnv_use_asdf _asdf_env_file` without checking whether it actually generated a file. However, that script exits early if it finds a problem (such as when a requested tool version isn't installed), so it might not generate an env file and its output might be empty. In that case the shim will try to `source_env ""`, causing direnv to produce a confusing message "referenced  does not exist". This patch just checks whether the `_asdf_env_file`  command generated a file before trying to source it.
The current behaviour:
```
$ echo use asdf elixir 1.10.0 > .envrc
direnv: error /home/evhan/code/asdf-direnv/.envrc is blocked. Run `direnv allow` to approve its content
$ direnv allow
direnv: loading ~/code/asdf-direnv/.envrc …
```
=> Check for successful env file generation before trying to source_env

bin/install
uname -m on the new M1 mac reports arm64 and doesn't match anything as a result.
=> Add support for Darwin on arm

README.md
This would be ideal, so that nobody has to update the `README` again the next release:
```bash
asdf install direnv latest
asdf global  direnv latest
```
However, this line seems to not work:
```bash
asdf global  direnv latest
```
=> Bump version shown in readme

lib/commands/command-hook-asdf.bash, lib/commands/command.bash
More robust error handling
I really like this plugin, but I think the error messages and behavior
when you don't have the right plugins installed (or the wrong versions
of those binaries provided by plugins) could be improved. That's what
I've done here:
- Prevent creating the cached env file if there are any errors.
- Raise an error if we depend on a plugin that isn't installed. (This
fixes https://github.com/asdf-community/asdf-direnv/issues/49)
- Raise an error if we depend on a version of a tool that isn't
installed.
Before
======
Setup:
$ cat .tool-versions
maven 3.8.4
$ cat .envrc
use asdf
Try loading direnv, note that we're missing the `maven` plugin:
$ direnv reload
direnv: loading ~/tmp/bugging/.envrc
direnv: using asdf
direnv: Creating env file …
=> More robust error handling

lib/commands/command.bash
This fixes https://github.com/asdf-community/asdf-direnv/issues/90.
This doesn't feel like the most elegant solution: it feels a little
strange that we can't detect situations where the user asks for say a
system python. However, after digging through asdf source code, I don't
think asdf *itself* really has any concept of "is this system version of
this thing installed" or not. Here's the relevant code:
https://github.com/asdf-vm/asdf/blob/9ee24a3a75e28ca0757d0b99fa00ce49466777a8/lib/utils.bash#L548-L552.
This doesn't really check if the system version exists, it just says
"ok, we'll run with an unmodified environment".
=> Don't bother checking if a "system" version of a plugin is installed.

lib/commands/command.bash
This fixes #95
This also drops support for older versions of `asdf` that have a
`utils.sh` file instead of a `utils.bash` file. That change happened way
back in asdf 0.7.7 in March 2020:
asdf-vm/asdf@52cbf11,
so I think it's safe to drop support by now.
=> Alternative way of loading asdf utils

lib/commands/command.bash
Handle special characters in the watch patch.
This fixes https://github.com/asdf-community/asdf-direnv/issues/67. All
credit for this fix should go to @MaienM. I had no idea `printf` had
this `%q` formatter, it's terribly useful!
Regarding portability: this is not my area of expertise, but this seems
to work fine for me on Linux and macOS:
Linux with Bash 5.1.16:
➜  ~ bash --version && bash
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
$ uname
Linux
$ printf "escaped: %q\n" "hello's world"
escaped: hello\'s\ world
macOS with Bash …
=> Handle special characters in the watch patch.

.editorconfig, Makefile
I spent some time this weekend getting my neovim configuration polished
up for working on shell scripts.
Once I got my editor auto-running `shfmt` for me, I found some
differences started to arise (for example, it was de-indenting all our
switch statements). Turns out we invoke `shfmt` with some non-default
settings (such as `-ci`), and my editor didn't know about that. I poked
around a little bit hoping to find some custom `.shfmtrc` file or
something we could put in the root of our repo. Turns out shfmt actually
knows about `.editorconfig` files, which we already have in this repo!
From
https://github.com/mvdan/sh/blob/master/cmd/shfmt/shfmt.1.scd#description:
> If any EditorConfig files are found, they will be used to apply
> formatting options. If any parser or printer flags are given …
=> Use EditorConfig for shfmt "parser or printer flags"

lib/commands/command.bash
This fixes https://github.com/asdf-community/asdf-direnv/issues/103.
Previously, we were putting the cached envrc files in a direnv specific
directory. This worked if `asdf where direnv` actually returns
a legitimate directory, but when you're using a system install of
direnv, `asdf where direnv` just prints out something like "System
version is selected", and that's not a directory we can work with.
I opted to allocate ourselves a directory under `XDG_CACHE_HOME`, which
has the nice property of always working, and also feels more appropriate
to me: these files aren't really a direnv thing, they're an
`asdf-direnv` thing.
=> Use a different directory for cached envrc files.

lib/commands/command.bash, test/use_asdf.bats
We no longer use asdf's `with_plugin_env`, since
it by default prepends custom-shims higher in path
which caused some issues as documented on #82.
We still add the shims directory (we had a test for
this) but now just after the actual installed bins.
We also use `source_env` to load the plugin's `exec-env`
with the added benefit that direnv will watch the file
for changes and re-trigger if people upgrade the plugin.
Fixes #82
=> Custom plugin shims now lower in PATH than bins

lib/commands/command.bash
In https://github.com/asdf-community/asdf-direnv/pull/110/, we changed
things so the generated envrc file is different based on if the
`ASDF_DIRENV_DEBUG` environment variable is set. Before this change, if
you were to generate a cached file while this env var is set, when you
switch the env var off, you'd *still* have a `set -x` in your cached
envrc file.
=> Add `ASDF_DIRENV_DEBUG` to the tools file checksum.

lib/commands/command.bash
I have `direnv` installed as a `system` version in `asdf`. With the current `asdf-direnv`, `/bin` ends up in my `PATH` before the original `PATH` entries. I use `coreutils` via homebrew instead of the BSD equivalents, and `/bin` coming before them causes some errors in my environment. This happens because when the cached env file is generated, `install_path` is an empty string for `system` plugins, `/bin` is appended to that `install_path`, and `PATH_add /bin` is added to the cached env file. Here is an env file that was created with the latest `asdf-direnv`:
```
log_status using asdf python 3.9.10
PATH_add /Users/bryan/.local/share/asdf/installs/python/3.9.10/bin
log_status using asdf direnv system
PATH_add /bin
watch_file /Users/bryan/.tool-versions
```
Surrounding the routine to add …
=> Do not add plugin paths for "system" versions

CHANGELOG.md, README.md
Using this variable results in speeding up things since we can avoid using asdf version resolution for direnv.
This makes even more sense when using a system installed version.
Also make the problem/solution sections on readme collapsible.
Related: #80
=> Write documentation about ASDF_DIRENV_BIN

.gitignore, CHANGELOG.md, README.md, lib/commands/command-local.bash, lib/commands/command-setup.bash, lib/setup-lib.bash, test/local_command.bats, test/setup_command.bats, test/test_helpers.bash
These commands follow our documented steps for setting up
asdf-direnv, both on system setup and on per-project.
The motivation is to lower the amount of work new people
has to do in order to get started with asdf-direnv.
=> Add `asdf direnv setup` and `asdf direnv local`.

.github/workflows/workflow.yml, CHANGELOG.md, Makefile, README.md, lib/commands/command-shell.bash, lib/commands/command.bash, test/shell_command.bats
Last week, I learned that @chris-lasher-honor used to be an
`asdf-direnv` user, but switched back to plain `asdf` because he liked
using `asdf shell` for small one-off commands like `npx
create-react-app`. I think that's a pretty solid use-case where it's not
necessarily worth the overhead of creating a `.tool-versions` file and a
`.envrc` file just to create a brand new folder that's going to also needs
its own set of the same dotfiles.
I also sometimes find that the activation energy necessary just to play
around with a random tool is a bit high with asdf-direnv:
- create a new directory
- run `asdf local <plugin> <version>`
- create a `.envrc` file
- run `direnv allow`
Now, you can do something like `asdf shell python 3.8.10`, and be up and
running immediately:
$ asdf current
direnv …
=> RFC: Add a new `asdf direnv shell` command

lib/setup-lib.bash
Fixes
```
No direnv executable found. Please do one of the following:
With a system installed direnv
export ASDF_DIRENV_BIN="$(command -v direnv)"
With an asdf installed direnv
export ASDF_DIRENV_BIN="$(asdf which direnv)"
```
=> fix: export direnv bin

README.md
Now that we have `setup` command, it should do everything users need.
If something fails badly, it's probably an issue that should be reported.
fixes #125
=> Remove manual instructions.

lib/setup-lib.bash, test/setup_command.bats
We're already setting a `ASDF_DIRENV_BIN` environment variable, it's
quite straightforward to reuse. I think this will make life a little easier
when people are upgrading direnv.
Before
======
Note how the full path to direnv (including the 2.31.0 version number)
shows up twice here:
$ asdf direnv setup fish
$ cat /home/jeremy/.config/fish/conf.d/asdf_direnv.fish
set -gx ASDF_DIRENV_BIN "/home/jeremy/.asdf/installs/direnv/2.31.0/bin/direnv"
/home/jeremy/.asdf/installs/direnv/2.31.0/bin/direnv hook fish | source
After
=====
$ asdf direnv setup fish
$ cat /home/jeremy/.config/fish/conf.d/asdf_direnv.fish
set -gx ASDF_DIRENV_BIN "/home/jeremy/.asdf/installs/direnv/2.31.0/bin/direnv"
$ASDF_DIRENV_BIN hook fish | source
=> DRY up the config a bit.

README.md, lib/setup-lib.bash, test/setup_command.bats
This may be personal preference, but I'd prefer to have a command to run
that doesn't ask for my input. This opens up the possibility of
scripting the setup of future laptops without an annoying prompt showing
up midway through.
I also removed the autodetection logic (`bin="${ASDF_DIRENV_BIN:-$(asdf
which direnv 2>/dev/null || true)}"`). I personally found it pretty
confusing, I think it's better to just make the user explicitly pick
what they want. This way, if they set things up one way, and later want
to switch to a system direnv, they can just re-run this script, rather
than knowing that they have to unset the `ASDF_DIRENV_BIN` variable
first.
=> Make `asdf direnv setup` non-interactive

lib/setup-lib.bash, test/setup_command.bats
This change allows the setup script to find the correct path to the zshrc file when [`ZDOTDIR`](https://zsh.sourceforge.io/Intro/intro_3.html) has been set.
This uses string substitution similar to the detection for the fish configuration file.
N/A, I think.
Added a test for `ZDOTDIR` being set.
Also ensured `ZDOTDIR` was unset for the original test.
~I apologize, but I'm not actually sure how to run the tests.~ Perhaps consider adding a Development section to the README in the future? Or maybe I can add one once I figure some things out. Anyways, ❤️ for asdf-direnv.
**UPDATE**: I was able to figure out how to run the tests with `bats-core` installed. I'm not sure how to get a test where the zsh files are all rolled back between the two zsh tests, though. Maybe that's okay for now.
=> Use ZDOTDIR to find zshrc, if set.

lib/tools-environment-lib.bash, test/test_helpers.bash, test/use_asdf.bats
asdf supports specifying a version like 'latest:3' which means the latest stable version, in the 3.x.y series of a program. This adds support for this feature in this plugin.
Also adds a test, and support for `list-all` in the test dummy plugin. `list-all` is called by asdf internally when using the 'latest:X' format.
`.tool-versions`:
```
shfmt latest:3
```
```
❯ direnv reload
direnv: using asdf
direnv: Creating env file /Users/amrox/.cache/asdf-direnv/env/2823755088-4041093217-1715707609-2415048703
direnv:  latest:3 not installed. Run 'asdf install' and then 'direnv reload'.
direnv: loading ~/.cache/asdf-direnv/env/2823755088-4041093217-1715707609-2415048703
direnv: using asdf shfmt latest:3
direnv: loading ~/tmp/asdf-direnv-latest/.envrc
❯ which shfmt
shfmt not found
```
```
❯ direnv …
```
=> Add support for resolving 'latest:X' in .tool-versions

lib/setup-lib.bash, test/test_helpers.bash
Instead of using asdf which, we now ensure to remove asdf shims from PATH and run `command -v direnv`.
Because it looks like `env ASDF_DIRENV_VERSION=system asdf which direnv` only works if you already have an asdf shim for direnv.
Also, run_cmd should exit with error status on failure
instead of continue executing setup.
Fixes #141
=> Dont use asdf which to look for system executables

lib/commands/command-_asdf_cached_envrc.bash, lib/commands/command-hook-asdf.bash
Some old `< 0.3.0 release` commands now show a deprecation notice along with instructions on how to upgrade and run the new `asdf direnv setup` command. We also instruct users to manually remove the old direnv integration from `~/.config/direnv/direnvrc` since it was previously part of our manual instructions.
Fixes #146
=> Help users upgrading from <0.3.0 without already having run `asdf direnv setup`.

lib/tools-environment-lib.bash
Fixes plugin bin paths setup when a plugin defines specific ones, as well as latest version resolution.
Refs https://github.com/asdf-community/asdf-direnv/issues/149#issuecomment-1106044956
Self explanatory.
None.
No tests added, perhaps some should be.
But I would **strongly** recommend making all scripts "strict mode" compliant. `set -u` / `nounset` mode would have immediately flagged this.
None. (Well apart from the strict mode consideration.)
=> _plugin_env_bash: fix plugin name variable use

lib/tools-environment-lib.bash
Fixes error on `asdf direnv local`:
```shellsession
$ asdf direnv local golang 1.18.2
▶ asdf plugin-add golang # ...  Plugin named golang already added
✔️
▶ asdf install golang 1.18.2 # ...  golang 1.18.2 is already installed
✔️
▶ asdf local golang 1.18.2 # ...  ✔️
✍  Modifying .envrc ✔️
▶ direnv allow # ...  ✔️
.../.asdf/plugins/direnv/lib/commands/../tools-environment-lib.bash:296: install_path: unbound variable
```
=> _plugin_env_bash: handle unset $install_path

lib/commands/command-envrc.bash, lib/tools-environment-lib.bash, test/test_helpers.bash, test/use_asdf.bats
NOTE: There are a few commits from https://github.com/asdf-community/asdf-direnv/pull/157 in this PR. They will go away once https://github.com/asdf-community/asdf-direnv/pull/157 is merged up.
This fixes https://github.com/asdf-community/asdf-direnv/issues/156
For some reason, it was super hard for me to write a reliable test of
this, but I'm happy with where I landed.
I'm not so happy with the implementation: I couldn't figure out any
clean way of doing this with command substitution. I think the problem is that
[command substitution screws up `set -e` semantics], but we also rely
upon those semantics throughout so much of our codebase it didn't feel
reasonable to me to try to change all those places. But, it's hard to
get rid of command substitution: it's how we return useful values …
=> Ensure cached env file does *not* get created when there are errors

.github/workflows/workflow.yml
I tried to switch us to `apt`, but that got messy: GitHub's `ubuntu-latest` currently points at `Ubuntu 20`, which doesn't have shfmt. We can opt into their [`ubuntu-22.04` beta](https://github.blog/changelog/2022-08-09-github-actions-ubuntu-22-04-is-now-generally-available-on-github-hosted-runners/), which does have `shfmt`, but the versions of `shfmt` and `shellcheck` are old enough that they aren't happy with how our code is currently written. So, I broke down and used this [`setup-homebrew` action](https://github.com/Homebrew/actions/tree/master/setup-homebrew) to get brew available and give us the latest versions of these tools.
This fixes https://github.com/asdf-community/asdf-direnv/issues/160
=> Keep brew available on Ubuntu

lib/setup-lib.bash
`asdf` v0.11.0 prepends `*` to the currently used version in the output of `asdf list <plugin>` like below.  
```
$ asdf list direnv
2.32.1
*2.32.2
```
So when `--version latest` is given, `installed_direnv()` function looks for a version prepended with `*` and fails.
```
$ asdf direnv setup --shell fish --version latest
Checking for asdf...
✔️  Found asdf at /home/toraja/.asdf/bin/asdf
Checking for direnv...
▶ asdf install direnv latest # ...  direnv 2.32.2 is already installed
✔️
▶ env ASDF_DIRENV_VERSION=*2.32.2 asdf which direnv # ...  No preset version installed for command direnv
Please install a version by running one of the following:
asdf install direnv *2.32.2
or add one of the following versions in your config file at /home/toraja/.tool-versions
direnv 2.32.1
direnv 2.32.2
❗️ …
```
=> Fix setup error with asdf v0.11

README.md
We added these instructions in
https://github.com/asdf-community/asdf-direnv/commit/d8067b6f783411035182dad0c004095f6afab68f, but it looks like they never actually worked.
I think the reason this didn't work is because the `direnv reload` process isn't the one to actually re-read the `.envrc` file, it just pokes some direnv internals such that the shell intergration will re-read it, and if your shell doesn't have this environment variable set, then debugging just won't get turned on.
Proof that env vars for the `direnv reload` process don't actually make it to the `.envrc` file:
Setup:
$ echo 'echo FOO IS ${FOO-}' > .envrc
direnv: error /home/jeremy/tmp/demo/.envrc is blocked. Run `direnv allow` to approve its content
$ direnv allow
direnv: loading ~/tmp/demo/.envrc
FOO IS
Now try …
=> Fix instructions for generating debug info

CHANGELOG.md, lib/tools-environment-lib.bash, test/use_asdf.bats
This fixes https://github.com/asdf-community/asdf-direnv/issues/159
A while back [we added support for
`latest:X`](https://github.com/asdf-community/asdf-direnv/commit/1c12032ffa1023e12effa193e918561d6554515f), but I don't think we ever verified if this worked for just plain `latest`. This copies the latest code from upstream, which requires importing the `latest_command` command from asdf itself.
=> Fix resolution of `latest`

CHANGELOG.md, lib/tools-environment-lib.bash
Fixes the following warning occurring since #177:
```text
direnv: loading ~/somedir/.envrc
direnv: using asdf
direnv: Creating env file /Users/foo/.cache/asdf-direnv/env/2102687569-1439381117-3323426503-1825845895
find: warning: you have specified the global option -maxdepth after the argument !, but global options are not positional, i.e., -maxdepth affects tests specified before it as well as those specified after it.  Please specify global options before other arguments.
find: warning: you have specified the global option -mindepth after the argument !, but global options are not positional, i.e., -mindepth affects tests specified before it as well as those specified after it.  Please specify global options before other arguments.
```
> Have you included tests (which could be a …
=> Fix warning on find

.github/workflows/workflow.yml
We use actionlint, which (among other things) runs shellcheck against the steps of our workflows. shellcheck doesn't like these variable references without surrounding double quotes. While I doubt either of these will ever contain a space, it's easier to just add the quotes to make shellcheck happy.
=> Appease shellcheck

lib/tools-environment-lib.bash
Fixes this error:
```
mktemp: mkstemp failed on /home/gv/.cache/asdf-direnv/env-generating/12442707-3712629820-2712272157-2840043161.XXXX: Invalid argument
```
...not enough Xs.
=> Fix for bsd mktemp

CHANGELOG.md, lib/commands/command-install.bash, lib/install-lib.bash, lib/tools-environment-lib.bash
Before this diff, it was difficult to install tools that depend on
other tools. For example, here's what happens if I try to install a
version of poetry on my machine:
$ asdf install poetry 1.5.1
No version is set for command python3
Consider adding one of the following versions in your config file at
python 3.10.2
python 3.8.10
curl: (23) Failure writing output to destination
Cleanup: Something went wrong!
48 /home/jeremy/.asdf/plugins/poetry/bin/install: POETRY_HOME=$install_path python3 - --version "$version" $flags
This is because my system doesn't actually have a global `python` or
`python3`. While I *could* install python with my system's package
manager, I'd rather re-use my asdf-managed python if at all possible.
Plus, poetry's installer doesn't even work with the 2 most popular …
=> Add a new `asdf direnv install` command

.github/workflows/workflow.yml
A few months ago, our GitHub actions started running on arm macOS
machines [0]. However, direnv v2.23.1 doesn't actually have an arm
release for macos:
https://github.com/direnv/direnv/releases/tag/v2.23.1. direnv started
uploading prebuild darwin-amd64 images in v2.28.0:
https://github.com/direnv/direnv/releases/tag/v2.28.0. I opted to just
upgrade us to the latest version while I'm in here.
[0]: https://www.reddit.com/r/github/comments/1cjiat4/is_github_actions_macoslatest_now_only_armbased/
=> Fix macOS build: upgrade to latest direnv

CHANGELOG.md, Makefile, lib/tools-environment-lib.bash, test/test_helpers.bash, test/use_asdf.bats
This change is to support the use of `ref:tag/branch/commit` and `path:/local/tool/version` tool versions.
Before: 😞 
After: 🥳 
The code replicates the `list_plugin_exec_paths()` behaviour from [`.asdf/lib/utils.bash`](https://github.com/asdf-vm/asdf/blob/ccdd47df9b73d0a22235eb06ad4c48eb57360832/lib/utils.bash#L534-L545) and integrates it into the `_plugin_env_bash()` version-resolution block.
Fixed Makefile target names.
Note the change in test helper also disables shellcheck SC2001 because we're matching the start of the string, which is not possible in a simple substitution.
The new tests cover both version types, with a necessary change to `dummy_bin_path()` to match the directory naming that's generated in [get_install_path()](https://github.com/asdf-vm/asdf/blob/ccdd47df9b73d0a22235e …
=> Support "ref:" and "path:" versions in .tool-versions
